# Generated by Django 3.1 on 2021-02-25 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0006_auto_20210225_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={'ordering': ('follower',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at',)},
        ),
    ]
