# Generated by Django 3.1 on 2021-03-01 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0007_auto_20210225_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='following',
            options={},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.RemoveField(
            model_name='post',
            name='wall',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wall.post'),
        ),
    ]
